### PR TITLE
fix: capacity scaling for 7.6 protocol

### LINKED ISSUE #1487: 7.6 cap is off by 100
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

On tibia7.6 when my cap is in the 300s, mehah/otclient will just show "cap 3".

For example, my real cap is 321, and otclient just show cap 3.

Observed on the ot server tibiafun.hopto.org on 4.0b4 and git master build

(Actually I think this bug has been around for a long time and I just never bothered reporting it)

Image

Image

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by divinity76**
# Description

On tibia7.6 when my cap is in the 300s, mehah/otclient will just show "cap 3".

For example, my real cap is 321, and otclient just show cap 3.

Observed on the ot server tibiafun.hopto.org on 4.0b4 and git master build

(Actually I think this bug has been around for a long time and I just never bothered reporting it)

Image

Image

## Behavior

cap displayed is 3

### **Actual**

have 321 cap

### **Expected**

show 321 cap

## Fixes

resolves https://github.com/mehah/otclient/issues/1487

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version: modified YurOTS 0.9.4F
  - Client: 4.0b4
  - Operating System: Windows 10 x64 22H2

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by luanluciano93 — APPROVED** [review]

**Comment by divinity76** [comment]
Wouldn't surprise me much if the "exact version" is 1281.

But, as I don't play any of 1280, 1281, or 1282 protocols, I don't care enough to double-check/confirm. 
(I pretty much only play 760)

File: src/client/protocolgameparse.cpp [hunk 1]
```diff
@@ -2319,7 +2319,11 @@ void ProtocolGame::parsePlayerStats(const InputMessagePtr& msg) const
 {
     const uint32_t health = g_game.getFeature(Otc::GameDoubleHealth) ? msg->getU32() : msg->getU16();
     const uint32_t maxHealth = g_game.getFeature(Otc::GameDoubleHealth) ? msg->getU32() : msg->getU16();
-    const uint32_t freeCapacity = g_game.getFeature(Otc::GameDoubleFreeCapacity) ? msg->getU32() / 100.f : msg->getU16() / 100.f;
+    uint32_t freeCapacity = g_game.getFeature(Otc::GameDoubleFreeCapacity) ? msg->getU32() : msg->getU16();
+    if (g_game.getClientVersion() > 760) {
```
Comment (kokekanon) [inline src/client/protocolgameparse.cpp]:
```suggestion
    if (g_game.getClientVersion() >= 772) {
```

image

**Review by kokekanon — CHANGES_REQUESTED** [review]

**Review by kokekanon — APPROVED** [review]
