### PR TITLE
rollback: UIItem onClick fix vbot issues #1520

### LINKED ISSUE #1520: Unable to remove items from vBot and Cavebot item lists
### Priority

High

### Area

- [ ] Data
- [ ] Source
- [x] Docker
- [ ] Other

### What happened?

custom compiled from git main, 1 january 2026,
When clicking on items inside item lists in either vBot_4.8 or cavebot_1.3, you're supposed to get a menu with a "clear item" option, 
but this option does not appear. nothing happens. not even a console error.

thus it is nigh-impossible to remove items from the item lists.

all vBot_4.8 and cavebot_1.3 item lists seem to be affected, including "Items to loot", "Containers for loot", "Sell Exceptions", "Container Panel", "Eatable Items"

Image

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kokekanon**
# Description

i bug that xD in **game_actionbar 3 bar pr**

image

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

https://github.com/mehah/otclient/issues/1520

## Type of change

Please delete options that are not relevant.

  - [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: modules/game_interface/widgets/uiitem.lua [hunk 1]
```diff
@@ -161,7 +161,7 @@ function UIItem:onMouseRelease(mousePosition, mouseButton)
         return false
     end
 
-    if modules.client_options.getOption('classicControl') and
+    if modules.client_options.getOption('classicControl') and not g_platform.isMobile() and
```
Comment (divinity76) [inline modules/game_interface/widgets/uiitem.lua:164]: ?

Comment (kokekanon) [reply modules/game_interface/widgets/uiitem.lua:164]: That's how it was before, that's why it's a "rollback".

image

File: modules/game_interface/widgets/uiitem.lua [hunk 2]
```diff
@@ -195,3 +195,21 @@ function UIItem:canAcceptDrop(widget, mousePos)
...
+        return
+    end
+
+    if modules.game_itemselector then
+        modules.game_itemselector.show(self)
+    end
+end
+
+function UIItem:onItemChange()
+    local tooltip = nil
```
Comment (divinity76) [inline modules/game_interface/widgets/uiitem.lua]: i imagine

```
self:setTooltip(nil);
```
is a type error? think it should be
```
    local tooltip = ""
```

unless you know setTooltip(nil) is safe?

**Review by divinity76 — APPROVED** [review]
can confirm this fix #1520

**Comment by divinity76** [comment]
Thank you! 🎉

File: modules/game_interface/widgets/uiitem.lua (hunk 2 above)
Comment (kokekanon) [reply modules/game_interface/widgets/uiitem.lua]: it's the same thing
image

Comment (divinity76) [reply modules/game_interface/widgets/uiitem.lua]: well on the c++ side i see
```cpp
    g_lua.bindClassMemberFunction<Item>("setTooltip", &Item::setTooltip);
```
and
```cpp
    void setTooltip(const std::string& str) { m_tooltip = str; }
```
maybe there is a null-guard in the c++<->lua glue somewhere tho, i just haven't spotted it (nor have i tested it)
