### PR TITLE
fix: skill Miniwindows in Old protocol

### LINKED ISSUE #1476: Special skills no visible
### Priority

Medium

### Area

- [x] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Critical skills and leach skills not visible on skill panel
Protocol 13.10 + Clean TFS (changed item to show bug)
```XML
	<item id="8882" article="an" name="earthborn titan armor">
		<attribute key="weight" value="12000" />
		<attribute key="slotType" value="body" />
		<attribute key="armor" value="15" />
		<attribute key="skillAxe" value="2" />
		<attribute key="absorbPercentEarth" value="5" />
		<attribute key="absorbPercentFire" value="-5" />
		<attribute key="lifeleechamount" value="1500" />
		<attribute key="lifeleechchance" value="100" />
		<attribute key="criticalhitchance" value="15" />
		<attribute key="criticalhitamount" value="25" />
	</item>
```
Cipsoft vs OTC
Image

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kokekanon**
- [x] 7.72
- [x] 860
- [x] 10.98
- [x] 12.91
- [x] 13.10
- [x] 13.32
- [x] 14.12

image image

image

### CODE REVIEW

File: modules/game_skills/skills.lua [hunk 1]
```diff
@@ -267,33 +276,18 @@ local function toggleGroupVisibility(groupName)
...
-                if childHeight <= 15 and childChildrenCount == 0 then
-                    child:setVisible(false)
-                end
-            end
-            hideUnnamedSeparators(child)
-        end
-    end
-    
-    hideUnnamedSeparators(skillsWindow)
+    setSkillGroupVisibility('misc', false)
```
Comment (ArturKnopik) [inline modules/game_skills/skills.lua]: Duplication

**Comment by ArturKnopik** [comment]
Maybe in case of fixes you can handle basis point percentage
for example 13.10 is sending percentage as numbers like 1234 thats mean 12,34%

https://github.com/mehah/otclient/blob/fa77ad0ebe75aff9eb49edcdf7a5a1f65741a464/src/client/protocolgameparse.cpp#L2412
https://github.com/mehah/otclient/blob/fa77ad0ebe75aff9eb49edcdf7a5a1f65741a464/src/client/protocolgameparse.cpp#L2432

**Comment by kokekanon** [comment]
image


image

**Comment by ArturKnopik** [comment]
@kokekanon cpp changes is required to propery handle basis points
try use this values for a test on QT and OTCR 13.10
```XML
<attribute key="lifeleechamount" value="1234" />
<attribute key="lifeleechchance" value="100" />
<attribute key="manaleechamount" value="1234" />
<attribute key="manaleechchance" value="99" />
```

**Comment by kokekanon** [comment]
@ArturKnopik 
??
```diff
	<item id="2494" article="a" name="demon armor">
		<attribute key="weight" value="8000" />
		<attribute key="armor" value="16" />
		<attribute key="slotType" value="body" />
+ <attribute key="lifeleechamount" value="1234" />
+ <attribute key="lifeleechchance" value="100" />
+ <attribute key="manaleechamount" value="1234" />
+ <attribute key="manaleechchance" value="99" />
	</item>
```

`/i 2494`
qt vs otc
image vs image 
image

note: My environment 13.10 does not have Forge to see that : fatal, dodge and momentum 

image

**Comment by ArturKnopik** [comment]
https://github.com/mehah/otclient/blob/8fa1bce2ff26e5e5f2211b676e269e3d3e8fd201/modules/game_skills/skills.lua#L1191
my changes
```LUA
function onMagicLevelChange(localPlayer, magiclevel, percent)
    setSkillValue('magiclevel', magiclevel)
    setSkillPercent('magiclevel',  percent/100, tr('You have %s percent to go', string.format("%.2f", 100 - (percent/100))))

    onBaseMagicLevelChange(localPlayer, localPlayer:getBaseMagicLevel())
end
```

https://github.com/mehah/otclient/blob/8fa1bce2ff26e5e5f2211b676e269e3d3e8fd201/modules/game_skills/skills.lua#L1202
```LUA
function onSkillChange(localPlayer, id, level, percent)
    setSkillValue('skillId' .. id, level)
    setSkillPercent('skillId' .. id, percent/100, tr('You have %s percent to go', string.format("%.2f", 100 - (percent/100))))

    onBaseSkillChange(localPlayer, id, localPlayer:getSkillBaseLevel(id))

    if id > Skill.ManaLeechAmount then
	    toggleSkill('skillId' .. id, level > 0)
    end
end
```

@kokekanon 
Looks good, idk how it's works without cpp changes thath i marked on secound post :D

**Comment by ArturKnopik** [comment]
> @ArturKnopik ??
> 
> ```diff
> 	<item id="2494" article="a" name="demon armor">
> 		<attribute key="weight" value="8000" />
> 		<attribute key="armor" value="16" />
> 		<attribute key="slotType" value="body" />
> + <attribute key="lifeleechamount" value="1234" />
> + <attribute key="lifeleechchance" value="100" />
> + <attribute key="manaleechamount" value="1234" />
> + <attribute key="manaleechchance" value="99" />
> 	</item>
> ```
> 
> `/i 2494` qt vs otc image vs image image
> 
> note: My environment 13.10 does not have Forge to see that : fatal, dodge and momentum
> 
> image

after secound check your values are wrong, should display 12,34 instead 578,64 for amount, qt also looks broken in this case ..

**Comment by kokekanon** [comment]
And how do you want me to fix the CipSoft client?


# 13.10

```cpp
            const uint16_t level = msg->getU16();
            const uint16_t baseLevel = msg->getU16();
            g_logger.warning("level: {} baseLevel {}", level,baseLevel);
            m_localPlayer->setSkill(static_cast<Otc::Skill>(skill), level, 0);
            m_localPlayer->setBaseSkill(static_cast<Otc::Skill>(skill), baseLevel);
```
```
WARNING: level: 0 baseLevel 0
WARNING: level: 100 baseLevel 0
WARNING: level: 57864 baseLevel 0
WARNING: level: 99 baseLevel 0
WARNING: level: 57864 baseLevel 0
```

# 13.21 canary
look canary  13.21
image
WARNING: level: 1334 baseLevel 100
WARNING: level: 1334 baseLevel 100

**1234** + 10 = 1334

## **It’s obvious that the problem is on the server side..."**

**Comment by ArturKnopik** [comment]
I know, i can show my fix for master code if needed

**Review by rodrigopaixaorj — APPROVED** [review]
